/**
 * This file is generated by the Taxi compiler.
 * Do not edit this file manually.
 */
import { DatatypeContainer, DatatypeName } from 'orbital-client';

function buildDatatypeContainer<V>(name: DatatypeName, value: V): DatatypeContainer<V> {
  return { name, value };
}

export namespace people {
  export type LastNameType = string;
  export type LastName = DatatypeContainer<LastNameType>;
  export type FirstNameType = string;
  export type FirstName = DatatypeContainer<FirstNameType>;
  export type AgeType = number;
  export type Age = DatatypeContainer<AgeType>;
  export type IsLivingType = boolean;
  export type IsLiving = DatatypeContainer<IsLivingType>;
  export type Person = DatatypeContainer<{
    readonly firstName: people.FirstNameType;
    readonly age: people.AgeType;
    readonly isLiving: people.IsLivingType
  }>;
  export class Taxonomy {
    readonly LastName: LastName = buildDatatypeContainer('people.LastName', '');
    readonly FirstName: FirstName = buildDatatypeContainer('people.FirstName', '');
    readonly Age: Age = buildDatatypeContainer('people.Age', 0);
    readonly IsLiving: IsLiving = buildDatatypeContainer('people.IsLiving', false);
    readonly Person: Person = buildDatatypeContainer('people.Person', {
      firstName: '',
      age: 0,
      isLiving: false,
    });
  }
}

export namespace animals {
  export type NameType = string;
  export type Name = DatatypeContainer<NameType>;
  export type Cow = DatatypeContainer<{ readonly name: animals.NameType; readonly age: people.AgeType }>;
  export class Taxonomy {
    readonly Name: Name = buildDatatypeContainer('animals.Name', '');
    readonly Cow: Cow = buildDatatypeContainer('animals.Cow', {
      name: '',
      age: 0,
    });
  }
}

export namespace animals.mammals {
  export type WeightType = number;
  export type Weight = DatatypeContainer<WeightType>;
  export type Whale = DatatypeContainer<{ readonly weight: animals.mammals.WeightType }>;
  export class Taxonomy {
    readonly Weight: Weight = buildDatatypeContainer('animals.mammals.Weight', 0);
    readonly Whale: Whale = buildDatatypeContainer('animals.mammals.Whale', {
      weight: 0,
    });
  }
}
export const taxonomy = {
  people: { ...(new people.Taxonomy()) },
  animals: { mammals: { ...(new animals.mammals.Taxonomy()) }, ...(new animals.Taxonomy()) },
};
